### ISSUE TITLE
Any way to dump a Bluetooth HID?

### ISSUE THREAD

**Issue by T-vK** [DIGImend/usbhid-dump#7]
Bluetooth devices can use the same HID report descripors as USB devices, do you think there is a way to use your tool to dump it for such a device? 

I really appreciate your tools and and all the work you've put into them, they worked well for me in the past.

**Comment by spbnick** [comment]
I'm way too late with this answer, just happened to be looking at DIGImend notifications. Still answering just in case.

Unfortunately, not. This is a USB-specific tool, and only speaks USB. However, you can likely see the Bluetooth HID report descriptor via the `/sys/kernel/debug` tree.
